name: "🐛 버그 수정"
description: "테스트 중 발생한 문제를 추적하기 위해 사용합니다."
title: "🐛 Bug: "
labels: ["Bug", "QA"]
body:
  - type: textarea
    id: symptom
    attributes:
      label: "📄 증상 설명"
      placeholder: "예) 특정 API 요청 시 500 에러가 발생합니다."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "🔍 재현 절차"
      placeholder: |
        1. 특정 API를 호출합니다.
        2. 예외가 발생하며 500 에러가 반환됩니다.
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: "🛠️ 테스트 환경"
      placeholder: "예) Local, Staging, Production"
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: "🖼️ 스크린샷 또는 로그"
      placeholder: "예)"
    validations:
      required: false
