name: "🧪 테스트 시나리오"
description: "기능 구현 후 검증을 위해 테스트를 요청할 때 사용합니다."
title: "🧪 Test: "
labels: ["QA", "Test"]
body:
  - type: textarea
    id: what-to-test
    attributes:
      label: "✅ 테스트 대상 기능"
      placeholder: "예) 회원가입 - 이메일 유효성 검증"
    validations:
      required: true

  - type: textarea
    id: test-checklist
    attributes:
      label: "🧾 테스트 체크리스트"
      placeholder: |
        - [ ] API 명세서에 맞게 응답이 오는지 확인
        - [ ] 예외 케이스에 대한 에러 처리가 올바르게 되는지 확인
      value: "- [ ] "
    validations:
      required: true

  - type: input
    id: test-environment
    attributes:
      label: "🧪 테스트 환경"
      placeholder: "예) Postman, Swagger UI"
    validations:
      required: false
