spring:
  application:
    name: tuk-api
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/tuk_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

firebase:
  admin-sdk: ${ENCODED_FIREBASE_ADMIN_SDK}
  enabled: true

springdoc:
  swagger-ui:
    path: /tuk-docs

management:
  endpoints:
    web:
      exposure:
        include: health

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
  apple:
    client-id: ${APPLE_CLIENT_ID}
    jwk-url: https://appleid.apple.com/auth/keys
    base-url: https://appleid.apple.com

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expires-in-days: 30
  refresh-token:
    expires-in-days: 90

slack:
  tokens:
    error-alert: ${SLACK_ERROR_ALERT_TOKEN}
  channels:
    error-alert: C099EEB4SQ7
  enabled: true

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/tuk_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
  apple:
    client-id: ${APPLE_CLIENT_ID}
    jwk-url: https://appleid.apple.com/auth/keys
    base-url: https://appleid.apple.com

---
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  config:
    activate:
      on-profile: test
oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID:test}
  apple:
    client-id: ${APPLE_CLIENT_ID:test}

jwt:
  secret: ${JWT_SECRET:myVeryLongSecretKeyThatIsAtLeast32CharactersLongForJWT}
  access-token:
    expires-in-days: 30
  refresh-token:
    expires-in-days: 90

firebase:
  admin-sdk: ${ENCODED_FIREBASE_ADMIN_SDK}
  enabled: false

slack:
  tokens:
    error-alert: ${SLACK_ERROR_ALERT_TOKEN:xoxb-myVeryLongSlackTokenThatIsAtLeast64CharactersLongForDevelopment}
  channels:
    error-alert: C099EEB4SQ7