spring:
  application:
    name: tuk-api
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/tuk_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /tuk-docs

management:
  endpoints:
    web:
      exposure:
        include: health

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expires-in-days: 1
  refresh-token:
    expires-in-days: 30

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: prod

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
